#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stp.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SS16_STP")]
	public partial class StpDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_COURSE_DEP(TBL_COURSE_DEP instance);
    partial void UpdateTBL_COURSE_DEP(TBL_COURSE_DEP instance);
    partial void DeleteTBL_COURSE_DEP(TBL_COURSE_DEP instance);
    partial void InsertTBL_COURSE_ORGANIZER(TBL_COURSE_ORGANIZER instance);
    partial void UpdateTBL_COURSE_ORGANIZER(TBL_COURSE_ORGANIZER instance);
    partial void DeleteTBL_COURSE_ORGANIZER(TBL_COURSE_ORGANIZER instance);
    partial void InsertTBL_COURSE_TEMPLATE(TBL_COURSE_TEMPLATE instance);
    partial void UpdateTBL_COURSE_TEMPLATE(TBL_COURSE_TEMPLATE instance);
    partial void DeleteTBL_COURSE_TEMPLATE(TBL_COURSE_TEMPLATE instance);
    partial void InsertTBL_COURSE_TRAINING(TBL_COURSE_TRAINING instance);
    partial void UpdateTBL_COURSE_TRAINING(TBL_COURSE_TRAINING instance);
    partial void DeleteTBL_COURSE_TRAINING(TBL_COURSE_TRAINING instance);
    partial void InsertTBL_DEPARTMENT(TBL_DEPARTMENT instance);
    partial void UpdateTBL_DEPARTMENT(TBL_DEPARTMENT instance);
    partial void DeleteTBL_DEPARTMENT(TBL_DEPARTMENT instance);
    partial void InsertTBL_EMPLOYEE(TBL_EMPLOYEE instance);
    partial void UpdateTBL_EMPLOYEE(TBL_EMPLOYEE instance);
    partial void DeleteTBL_EMPLOYEE(TBL_EMPLOYEE instance);
    partial void InsertTBL_PARTICIPANT_LIST(TBL_PARTICIPANT_LIST instance);
    partial void UpdateTBL_PARTICIPANT_LIST(TBL_PARTICIPANT_LIST instance);
    partial void DeleteTBL_PARTICIPANT_LIST(TBL_PARTICIPANT_LIST instance);
    partial void InsertTBL_ROOM(TBL_ROOM instance);
    partial void UpdateTBL_ROOM(TBL_ROOM instance);
    partial void DeleteTBL_ROOM(TBL_ROOM instance);
    #endregion
		
		public StpDataContext() : 
				base(global::stp.Properties.Settings.Default.SS16_STPConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public StpDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StpDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StpDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StpDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_COURSE_DEP> TBL_COURSE_DEPs
		{
			get
			{
				return this.GetTable<TBL_COURSE_DEP>();
			}
		}
		
		public System.Data.Linq.Table<TBL_COURSE_ORGANIZER> TBL_COURSE_ORGANIZERs
		{
			get
			{
				return this.GetTable<TBL_COURSE_ORGANIZER>();
			}
		}
		
		public System.Data.Linq.Table<TBL_COURSE_TEMPLATE> TBL_COURSE_TEMPLATEs
		{
			get
			{
				return this.GetTable<TBL_COURSE_TEMPLATE>();
			}
		}
		
		public System.Data.Linq.Table<TBL_COURSE_TRAINING> TBL_COURSE_TRAININGs
		{
			get
			{
				return this.GetTable<TBL_COURSE_TRAINING>();
			}
		}
		
		public System.Data.Linq.Table<TBL_DEPARTMENT> TBL_DEPARTMENTs
		{
			get
			{
				return this.GetTable<TBL_DEPARTMENT>();
			}
		}
		
		public System.Data.Linq.Table<TBL_EMPLOYEE> TBL_EMPLOYEEs
		{
			get
			{
				return this.GetTable<TBL_EMPLOYEE>();
			}
		}
		
		public System.Data.Linq.Table<TBL_PARTICIPANT_LIST> TBL_PARTICIPANT_LISTs
		{
			get
			{
				return this.GetTable<TBL_PARTICIPANT_LIST>();
			}
		}
		
		public System.Data.Linq.Table<TBL_ROOM> TBL_ROOMs
		{
			get
			{
				return this.GetTable<TBL_ROOM>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_COURSE_DEP")]
	public partial class TBL_COURSE_DEP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _fk_course;
		
		private int _fk_dep;
		
		private System.Nullable<int> _required;
		
		private EntityRef<TBL_COURSE_TEMPLATE> _TBL_COURSE_TEMPLATE;
		
		private EntityRef<TBL_DEPARTMENT> _TBL_DEPARTMENT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfk_courseChanging(int value);
    partial void Onfk_courseChanged();
    partial void Onfk_depChanging(int value);
    partial void Onfk_depChanged();
    partial void OnrequiredChanging(System.Nullable<int> value);
    partial void OnrequiredChanged();
    #endregion
		
		public TBL_COURSE_DEP()
		{
			this._TBL_COURSE_TEMPLATE = default(EntityRef<TBL_COURSE_TEMPLATE>);
			this._TBL_DEPARTMENT = default(EntityRef<TBL_DEPARTMENT>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_course", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int fk_course
		{
			get
			{
				return this._fk_course;
			}
			set
			{
				if ((this._fk_course != value))
				{
					if (this._TBL_COURSE_TEMPLATE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_courseChanging(value);
					this.SendPropertyChanging();
					this._fk_course = value;
					this.SendPropertyChanged("fk_course");
					this.Onfk_courseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_dep", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int fk_dep
		{
			get
			{
				return this._fk_dep;
			}
			set
			{
				if ((this._fk_dep != value))
				{
					if (this._TBL_DEPARTMENT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_depChanging(value);
					this.SendPropertyChanging();
					this._fk_dep = value;
					this.SendPropertyChanged("fk_dep");
					this.Onfk_depChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_required", DbType="Int")]
		public System.Nullable<int> required
		{
			get
			{
				return this._required;
			}
			set
			{
				if ((this._required != value))
				{
					this.OnrequiredChanging(value);
					this.SendPropertyChanging();
					this._required = value;
					this.SendPropertyChanged("required");
					this.OnrequiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_COURSE_TEMPLATE_TBL_COURSE_DEP", Storage="_TBL_COURSE_TEMPLATE", ThisKey="fk_course", OtherKey="ID", IsForeignKey=true)]
		public TBL_COURSE_TEMPLATE TBL_COURSE_TEMPLATE
		{
			get
			{
				return this._TBL_COURSE_TEMPLATE.Entity;
			}
			set
			{
				TBL_COURSE_TEMPLATE previousValue = this._TBL_COURSE_TEMPLATE.Entity;
				if (((previousValue != value) 
							|| (this._TBL_COURSE_TEMPLATE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_COURSE_TEMPLATE.Entity = null;
						previousValue.TBL_COURSE_DEPs.Remove(this);
					}
					this._TBL_COURSE_TEMPLATE.Entity = value;
					if ((value != null))
					{
						value.TBL_COURSE_DEPs.Add(this);
						this._fk_course = value.ID;
					}
					else
					{
						this._fk_course = default(int);
					}
					this.SendPropertyChanged("TBL_COURSE_TEMPLATE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_DEPARTMENT_TBL_COURSE_DEP", Storage="_TBL_DEPARTMENT", ThisKey="fk_dep", OtherKey="ID", IsForeignKey=true)]
		public TBL_DEPARTMENT TBL_DEPARTMENT
		{
			get
			{
				return this._TBL_DEPARTMENT.Entity;
			}
			set
			{
				TBL_DEPARTMENT previousValue = this._TBL_DEPARTMENT.Entity;
				if (((previousValue != value) 
							|| (this._TBL_DEPARTMENT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_DEPARTMENT.Entity = null;
						previousValue.TBL_COURSE_DEPs.Remove(this);
					}
					this._TBL_DEPARTMENT.Entity = value;
					if ((value != null))
					{
						value.TBL_COURSE_DEPs.Add(this);
						this._fk_dep = value.ID;
					}
					else
					{
						this._fk_dep = default(int);
					}
					this.SendPropertyChanged("TBL_DEPARTMENT");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_COURSE_ORGANIZER")]
	public partial class TBL_COURSE_ORGANIZER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _name;
		
		private string _phone;
		
		private string _mobil;
		
		private string _mail;
		
		private EntitySet<TBL_COURSE_TEMPLATE> _TBL_COURSE_TEMPLATEs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnmobilChanging(string value);
    partial void OnmobilChanged();
    partial void OnmailChanging(string value);
    partial void OnmailChanged();
    #endregion
		
		public TBL_COURSE_ORGANIZER()
		{
			this._TBL_COURSE_TEMPLATEs = new EntitySet<TBL_COURSE_TEMPLATE>(new Action<TBL_COURSE_TEMPLATE>(this.attach_TBL_COURSE_TEMPLATEs), new Action<TBL_COURSE_TEMPLATE>(this.detach_TBL_COURSE_TEMPLATEs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(255)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(255)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobil", DbType="VarChar(255)")]
		public string mobil
		{
			get
			{
				return this._mobil;
			}
			set
			{
				if ((this._mobil != value))
				{
					this.OnmobilChanging(value);
					this.SendPropertyChanging();
					this._mobil = value;
					this.SendPropertyChanged("mobil");
					this.OnmobilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mail", DbType="VarChar(255)")]
		public string mail
		{
			get
			{
				return this._mail;
			}
			set
			{
				if ((this._mail != value))
				{
					this.OnmailChanging(value);
					this.SendPropertyChanging();
					this._mail = value;
					this.SendPropertyChanged("mail");
					this.OnmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_COURSE_ORGANIZER_TBL_COURSE_TEMPLATE", Storage="_TBL_COURSE_TEMPLATEs", ThisKey="ID", OtherKey="fk_organizer")]
		public EntitySet<TBL_COURSE_TEMPLATE> TBL_COURSE_TEMPLATEs
		{
			get
			{
				return this._TBL_COURSE_TEMPLATEs;
			}
			set
			{
				this._TBL_COURSE_TEMPLATEs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_COURSE_TEMPLATEs(TBL_COURSE_TEMPLATE entity)
		{
			this.SendPropertyChanging();
			entity.TBL_COURSE_ORGANIZER = this;
		}
		
		private void detach_TBL_COURSE_TEMPLATEs(TBL_COURSE_TEMPLATE entity)
		{
			this.SendPropertyChanging();
			entity.TBL_COURSE_ORGANIZER = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_COURSE_TEMPLATE")]
	public partial class TBL_COURSE_TEMPLATE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _fk_organizer;
		
		private System.Nullable<int> _maxparticipent;
		
		private string _course_description;
		
		private string _short_name;
		
		private string _duration;
		
		private EntitySet<TBL_COURSE_DEP> _TBL_COURSE_DEPs;
		
		private EntitySet<TBL_COURSE_TRAINING> _TBL_COURSE_TRAININGs;
		
		private EntityRef<TBL_COURSE_ORGANIZER> _TBL_COURSE_ORGANIZER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void Onfk_organizerChanging(int value);
    partial void Onfk_organizerChanged();
    partial void OnmaxparticipentChanging(System.Nullable<int> value);
    partial void OnmaxparticipentChanged();
    partial void Oncourse_descriptionChanging(string value);
    partial void Oncourse_descriptionChanged();
    partial void Onshort_nameChanging(string value);
    partial void Onshort_nameChanged();
    partial void OndurationChanging(string value);
    partial void OndurationChanged();
    #endregion
		
		public TBL_COURSE_TEMPLATE()
		{
			this._TBL_COURSE_DEPs = new EntitySet<TBL_COURSE_DEP>(new Action<TBL_COURSE_DEP>(this.attach_TBL_COURSE_DEPs), new Action<TBL_COURSE_DEP>(this.detach_TBL_COURSE_DEPs));
			this._TBL_COURSE_TRAININGs = new EntitySet<TBL_COURSE_TRAINING>(new Action<TBL_COURSE_TRAINING>(this.attach_TBL_COURSE_TRAININGs), new Action<TBL_COURSE_TRAINING>(this.detach_TBL_COURSE_TRAININGs));
			this._TBL_COURSE_ORGANIZER = default(EntityRef<TBL_COURSE_ORGANIZER>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_organizer", DbType="Int NOT NULL")]
		public int fk_organizer
		{
			get
			{
				return this._fk_organizer;
			}
			set
			{
				if ((this._fk_organizer != value))
				{
					if (this._TBL_COURSE_ORGANIZER.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_organizerChanging(value);
					this.SendPropertyChanging();
					this._fk_organizer = value;
					this.SendPropertyChanged("fk_organizer");
					this.Onfk_organizerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxparticipent", DbType="Int")]
		public System.Nullable<int> maxparticipent
		{
			get
			{
				return this._maxparticipent;
			}
			set
			{
				if ((this._maxparticipent != value))
				{
					this.OnmaxparticipentChanging(value);
					this.SendPropertyChanging();
					this._maxparticipent = value;
					this.SendPropertyChanged("maxparticipent");
					this.OnmaxparticipentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_course_description", DbType="VarChar(1000)")]
		public string course_description
		{
			get
			{
				return this._course_description;
			}
			set
			{
				if ((this._course_description != value))
				{
					this.Oncourse_descriptionChanging(value);
					this.SendPropertyChanging();
					this._course_description = value;
					this.SendPropertyChanged("course_description");
					this.Oncourse_descriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_short_name", DbType="VarChar(50)")]
		public string short_name
		{
			get
			{
				return this._short_name;
			}
			set
			{
				if ((this._short_name != value))
				{
					this.Onshort_nameChanging(value);
					this.SendPropertyChanging();
					this._short_name = value;
					this.SendPropertyChanged("short_name");
					this.Onshort_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duration", DbType="VarChar(50)")]
		public string duration
		{
			get
			{
				return this._duration;
			}
			set
			{
				if ((this._duration != value))
				{
					this.OndurationChanging(value);
					this.SendPropertyChanging();
					this._duration = value;
					this.SendPropertyChanged("duration");
					this.OndurationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_COURSE_TEMPLATE_TBL_COURSE_DEP", Storage="_TBL_COURSE_DEPs", ThisKey="ID", OtherKey="fk_course")]
		public EntitySet<TBL_COURSE_DEP> TBL_COURSE_DEPs
		{
			get
			{
				return this._TBL_COURSE_DEPs;
			}
			set
			{
				this._TBL_COURSE_DEPs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_COURSE_TEMPLATE_TBL_COURSE_TRAINING", Storage="_TBL_COURSE_TRAININGs", ThisKey="ID", OtherKey="fk_course")]
		public EntitySet<TBL_COURSE_TRAINING> TBL_COURSE_TRAININGs
		{
			get
			{
				return this._TBL_COURSE_TRAININGs;
			}
			set
			{
				this._TBL_COURSE_TRAININGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_COURSE_ORGANIZER_TBL_COURSE_TEMPLATE", Storage="_TBL_COURSE_ORGANIZER", ThisKey="fk_organizer", OtherKey="ID", IsForeignKey=true)]
		public TBL_COURSE_ORGANIZER TBL_COURSE_ORGANIZER
		{
			get
			{
				return this._TBL_COURSE_ORGANIZER.Entity;
			}
			set
			{
				TBL_COURSE_ORGANIZER previousValue = this._TBL_COURSE_ORGANIZER.Entity;
				if (((previousValue != value) 
							|| (this._TBL_COURSE_ORGANIZER.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_COURSE_ORGANIZER.Entity = null;
						previousValue.TBL_COURSE_TEMPLATEs.Remove(this);
					}
					this._TBL_COURSE_ORGANIZER.Entity = value;
					if ((value != null))
					{
						value.TBL_COURSE_TEMPLATEs.Add(this);
						this._fk_organizer = value.ID;
					}
					else
					{
						this._fk_organizer = default(int);
					}
					this.SendPropertyChanged("TBL_COURSE_ORGANIZER");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_COURSE_DEPs(TBL_COURSE_DEP entity)
		{
			this.SendPropertyChanging();
			entity.TBL_COURSE_TEMPLATE = this;
		}
		
		private void detach_TBL_COURSE_DEPs(TBL_COURSE_DEP entity)
		{
			this.SendPropertyChanging();
			entity.TBL_COURSE_TEMPLATE = null;
		}
		
		private void attach_TBL_COURSE_TRAININGs(TBL_COURSE_TRAINING entity)
		{
			this.SendPropertyChanging();
			entity.TBL_COURSE_TEMPLATE = this;
		}
		
		private void detach_TBL_COURSE_TRAININGs(TBL_COURSE_TRAINING entity)
		{
			this.SendPropertyChanging();
			entity.TBL_COURSE_TEMPLATE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_COURSE_TRAINING")]
	public partial class TBL_COURSE_TRAINING : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _fk_course;
		
		private int _fk_room;
		
		private System.Nullable<int> _fk_emp;
		
		private System.Nullable<int> _max_people;
		
		private System.Nullable<System.DateTime> _date;
		
		private System.Nullable<System.TimeSpan> _duration;
		
		private string _desc;
		
		private EntitySet<TBL_PARTICIPANT_LIST> _TBL_PARTICIPANT_LISTs;
		
		private EntityRef<TBL_COURSE_TEMPLATE> _TBL_COURSE_TEMPLATE;
		
		private EntityRef<TBL_EMPLOYEE> _TBL_EMPLOYEE;
		
		private EntityRef<TBL_ROOM> _TBL_ROOM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void Onfk_courseChanging(int value);
    partial void Onfk_courseChanged();
    partial void Onfk_roomChanging(int value);
    partial void Onfk_roomChanged();
    partial void Onfk_empChanging(System.Nullable<int> value);
    partial void Onfk_empChanged();
    partial void Onmax_peopleChanging(System.Nullable<int> value);
    partial void Onmax_peopleChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void OndurationChanging(System.Nullable<System.TimeSpan> value);
    partial void OndurationChanged();
    partial void OndescChanging(string value);
    partial void OndescChanged();
    #endregion
		
		public TBL_COURSE_TRAINING()
		{
			this._TBL_PARTICIPANT_LISTs = new EntitySet<TBL_PARTICIPANT_LIST>(new Action<TBL_PARTICIPANT_LIST>(this.attach_TBL_PARTICIPANT_LISTs), new Action<TBL_PARTICIPANT_LIST>(this.detach_TBL_PARTICIPANT_LISTs));
			this._TBL_COURSE_TEMPLATE = default(EntityRef<TBL_COURSE_TEMPLATE>);
			this._TBL_EMPLOYEE = default(EntityRef<TBL_EMPLOYEE>);
			this._TBL_ROOM = default(EntityRef<TBL_ROOM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_course", DbType="Int NOT NULL")]
		public int fk_course
		{
			get
			{
				return this._fk_course;
			}
			set
			{
				if ((this._fk_course != value))
				{
					if (this._TBL_COURSE_TEMPLATE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_courseChanging(value);
					this.SendPropertyChanging();
					this._fk_course = value;
					this.SendPropertyChanged("fk_course");
					this.Onfk_courseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_room", DbType="Int NOT NULL")]
		public int fk_room
		{
			get
			{
				return this._fk_room;
			}
			set
			{
				if ((this._fk_room != value))
				{
					if (this._TBL_ROOM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_roomChanging(value);
					this.SendPropertyChanging();
					this._fk_room = value;
					this.SendPropertyChanged("fk_room");
					this.Onfk_roomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_emp", DbType="Int")]
		public System.Nullable<int> fk_emp
		{
			get
			{
				return this._fk_emp;
			}
			set
			{
				if ((this._fk_emp != value))
				{
					if (this._TBL_EMPLOYEE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_empChanging(value);
					this.SendPropertyChanging();
					this._fk_emp = value;
					this.SendPropertyChanged("fk_emp");
					this.Onfk_empChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_max_people", DbType="Int")]
		public System.Nullable<int> max_people
		{
			get
			{
				return this._max_people;
			}
			set
			{
				if ((this._max_people != value))
				{
					this.Onmax_peopleChanging(value);
					this.SendPropertyChanging();
					this._max_people = value;
					this.SendPropertyChanged("max_people");
					this.Onmax_peopleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="Date")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duration", DbType="Time")]
		public System.Nullable<System.TimeSpan> duration
		{
			get
			{
				return this._duration;
			}
			set
			{
				if ((this._duration != value))
				{
					this.OndurationChanging(value);
					this.SendPropertyChanging();
					this._duration = value;
					this.SendPropertyChanged("duration");
					this.OndurationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[desc]", Storage="_desc", DbType="VarChar(255)")]
		public string desc
		{
			get
			{
				return this._desc;
			}
			set
			{
				if ((this._desc != value))
				{
					this.OndescChanging(value);
					this.SendPropertyChanging();
					this._desc = value;
					this.SendPropertyChanged("desc");
					this.OndescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_COURSE_TRAINING_TBL_PARTICIPANT_LIST", Storage="_TBL_PARTICIPANT_LISTs", ThisKey="ID", OtherKey="fk_training")]
		public EntitySet<TBL_PARTICIPANT_LIST> TBL_PARTICIPANT_LISTs
		{
			get
			{
				return this._TBL_PARTICIPANT_LISTs;
			}
			set
			{
				this._TBL_PARTICIPANT_LISTs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_COURSE_TEMPLATE_TBL_COURSE_TRAINING", Storage="_TBL_COURSE_TEMPLATE", ThisKey="fk_course", OtherKey="ID", IsForeignKey=true)]
		public TBL_COURSE_TEMPLATE TBL_COURSE_TEMPLATE
		{
			get
			{
				return this._TBL_COURSE_TEMPLATE.Entity;
			}
			set
			{
				TBL_COURSE_TEMPLATE previousValue = this._TBL_COURSE_TEMPLATE.Entity;
				if (((previousValue != value) 
							|| (this._TBL_COURSE_TEMPLATE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_COURSE_TEMPLATE.Entity = null;
						previousValue.TBL_COURSE_TRAININGs.Remove(this);
					}
					this._TBL_COURSE_TEMPLATE.Entity = value;
					if ((value != null))
					{
						value.TBL_COURSE_TRAININGs.Add(this);
						this._fk_course = value.ID;
					}
					else
					{
						this._fk_course = default(int);
					}
					this.SendPropertyChanged("TBL_COURSE_TEMPLATE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_EMPLOYEE_TBL_COURSE_TRAINING", Storage="_TBL_EMPLOYEE", ThisKey="fk_emp", OtherKey="ID", IsForeignKey=true)]
		public TBL_EMPLOYEE TBL_EMPLOYEE
		{
			get
			{
				return this._TBL_EMPLOYEE.Entity;
			}
			set
			{
				TBL_EMPLOYEE previousValue = this._TBL_EMPLOYEE.Entity;
				if (((previousValue != value) 
							|| (this._TBL_EMPLOYEE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_EMPLOYEE.Entity = null;
						previousValue.TBL_COURSE_TRAININGs.Remove(this);
					}
					this._TBL_EMPLOYEE.Entity = value;
					if ((value != null))
					{
						value.TBL_COURSE_TRAININGs.Add(this);
						this._fk_emp = value.ID;
					}
					else
					{
						this._fk_emp = default(Nullable<int>);
					}
					this.SendPropertyChanged("TBL_EMPLOYEE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_ROOM_TBL_COURSE_TRAINING", Storage="_TBL_ROOM", ThisKey="fk_room", OtherKey="ID", IsForeignKey=true)]
		public TBL_ROOM TBL_ROOM
		{
			get
			{
				return this._TBL_ROOM.Entity;
			}
			set
			{
				TBL_ROOM previousValue = this._TBL_ROOM.Entity;
				if (((previousValue != value) 
							|| (this._TBL_ROOM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_ROOM.Entity = null;
						previousValue.TBL_COURSE_TRAININGs.Remove(this);
					}
					this._TBL_ROOM.Entity = value;
					if ((value != null))
					{
						value.TBL_COURSE_TRAININGs.Add(this);
						this._fk_room = value.ID;
					}
					else
					{
						this._fk_room = default(int);
					}
					this.SendPropertyChanged("TBL_ROOM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_PARTICIPANT_LISTs(TBL_PARTICIPANT_LIST entity)
		{
			this.SendPropertyChanging();
			entity.TBL_COURSE_TRAINING = this;
		}
		
		private void detach_TBL_PARTICIPANT_LISTs(TBL_PARTICIPANT_LIST entity)
		{
			this.SendPropertyChanging();
			entity.TBL_COURSE_TRAINING = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_DEPARTMENT")]
	public partial class TBL_DEPARTMENT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _name;
		
		private EntitySet<TBL_COURSE_DEP> _TBL_COURSE_DEPs;
		
		private EntitySet<TBL_EMPLOYEE> _TBL_EMPLOYEEs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public TBL_DEPARTMENT()
		{
			this._TBL_COURSE_DEPs = new EntitySet<TBL_COURSE_DEP>(new Action<TBL_COURSE_DEP>(this.attach_TBL_COURSE_DEPs), new Action<TBL_COURSE_DEP>(this.detach_TBL_COURSE_DEPs));
			this._TBL_EMPLOYEEs = new EntitySet<TBL_EMPLOYEE>(new Action<TBL_EMPLOYEE>(this.attach_TBL_EMPLOYEEs), new Action<TBL_EMPLOYEE>(this.detach_TBL_EMPLOYEEs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(255)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_DEPARTMENT_TBL_COURSE_DEP", Storage="_TBL_COURSE_DEPs", ThisKey="ID", OtherKey="fk_dep")]
		public EntitySet<TBL_COURSE_DEP> TBL_COURSE_DEPs
		{
			get
			{
				return this._TBL_COURSE_DEPs;
			}
			set
			{
				this._TBL_COURSE_DEPs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_DEPARTMENT_TBL_EMPLOYEE", Storage="_TBL_EMPLOYEEs", ThisKey="ID", OtherKey="fk_dep")]
		public EntitySet<TBL_EMPLOYEE> TBL_EMPLOYEEs
		{
			get
			{
				return this._TBL_EMPLOYEEs;
			}
			set
			{
				this._TBL_EMPLOYEEs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_COURSE_DEPs(TBL_COURSE_DEP entity)
		{
			this.SendPropertyChanging();
			entity.TBL_DEPARTMENT = this;
		}
		
		private void detach_TBL_COURSE_DEPs(TBL_COURSE_DEP entity)
		{
			this.SendPropertyChanging();
			entity.TBL_DEPARTMENT = null;
		}
		
		private void attach_TBL_EMPLOYEEs(TBL_EMPLOYEE entity)
		{
			this.SendPropertyChanging();
			entity.TBL_DEPARTMENT = this;
		}
		
		private void detach_TBL_EMPLOYEEs(TBL_EMPLOYEE entity)
		{
			this.SendPropertyChanging();
			entity.TBL_DEPARTMENT = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_EMPLOYEE")]
	public partial class TBL_EMPLOYEE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _name;
		
		private string _firstName;
		
		private string _city;
		
		private System.Nullable<System.DateTime> _birth;
		
		private string _email;
		
		private System.Nullable<System.DateTime> _date_of_joining;
		
		private System.Nullable<int> _fk_dep;
		
		private System.Nullable<bool> _status;
		
		private EntitySet<TBL_COURSE_TRAINING> _TBL_COURSE_TRAININGs;
		
		private EntitySet<TBL_PARTICIPANT_LIST> _TBL_PARTICIPANT_LISTs;
		
		private EntityRef<TBL_DEPARTMENT> _TBL_DEPARTMENT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnfirstNameChanging(string value);
    partial void OnfirstNameChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnbirthChanging(System.Nullable<System.DateTime> value);
    partial void OnbirthChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Ondate_of_joiningChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_of_joiningChanged();
    partial void Onfk_depChanging(System.Nullable<int> value);
    partial void Onfk_depChanged();
    partial void OnstatusChanging(System.Nullable<bool> value);
    partial void OnstatusChanged();
    #endregion
		
		public TBL_EMPLOYEE()
		{
			this._TBL_COURSE_TRAININGs = new EntitySet<TBL_COURSE_TRAINING>(new Action<TBL_COURSE_TRAINING>(this.attach_TBL_COURSE_TRAININGs), new Action<TBL_COURSE_TRAINING>(this.detach_TBL_COURSE_TRAININGs));
			this._TBL_PARTICIPANT_LISTs = new EntitySet<TBL_PARTICIPANT_LIST>(new Action<TBL_PARTICIPANT_LIST>(this.attach_TBL_PARTICIPANT_LISTs), new Action<TBL_PARTICIPANT_LIST>(this.detach_TBL_PARTICIPANT_LISTs));
			this._TBL_DEPARTMENT = default(EntityRef<TBL_DEPARTMENT>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(255)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstName", DbType="VarChar(255)")]
		public string firstName
		{
			get
			{
				return this._firstName;
			}
			set
			{
				if ((this._firstName != value))
				{
					this.OnfirstNameChanging(value);
					this.SendPropertyChanging();
					this._firstName = value;
					this.SendPropertyChanged("firstName");
					this.OnfirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(255)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birth", DbType="Date")]
		public System.Nullable<System.DateTime> birth
		{
			get
			{
				return this._birth;
			}
			set
			{
				if ((this._birth != value))
				{
					this.OnbirthChanging(value);
					this.SendPropertyChanging();
					this._birth = value;
					this.SendPropertyChanged("birth");
					this.OnbirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(255)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_of_joining", DbType="Date")]
		public System.Nullable<System.DateTime> date_of_joining
		{
			get
			{
				return this._date_of_joining;
			}
			set
			{
				if ((this._date_of_joining != value))
				{
					this.Ondate_of_joiningChanging(value);
					this.SendPropertyChanging();
					this._date_of_joining = value;
					this.SendPropertyChanged("date_of_joining");
					this.Ondate_of_joiningChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_dep", DbType="Int")]
		public System.Nullable<int> fk_dep
		{
			get
			{
				return this._fk_dep;
			}
			set
			{
				if ((this._fk_dep != value))
				{
					if (this._TBL_DEPARTMENT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_depChanging(value);
					this.SendPropertyChanging();
					this._fk_dep = value;
					this.SendPropertyChanged("fk_dep");
					this.Onfk_depChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Bit")]
		public System.Nullable<bool> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_EMPLOYEE_TBL_COURSE_TRAINING", Storage="_TBL_COURSE_TRAININGs", ThisKey="ID", OtherKey="fk_emp")]
		public EntitySet<TBL_COURSE_TRAINING> TBL_COURSE_TRAININGs
		{
			get
			{
				return this._TBL_COURSE_TRAININGs;
			}
			set
			{
				this._TBL_COURSE_TRAININGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_EMPLOYEE_TBL_PARTICIPANT_LIST", Storage="_TBL_PARTICIPANT_LISTs", ThisKey="ID", OtherKey="fk_emp")]
		public EntitySet<TBL_PARTICIPANT_LIST> TBL_PARTICIPANT_LISTs
		{
			get
			{
				return this._TBL_PARTICIPANT_LISTs;
			}
			set
			{
				this._TBL_PARTICIPANT_LISTs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_DEPARTMENT_TBL_EMPLOYEE", Storage="_TBL_DEPARTMENT", ThisKey="fk_dep", OtherKey="ID", IsForeignKey=true)]
		public TBL_DEPARTMENT TBL_DEPARTMENT
		{
			get
			{
				return this._TBL_DEPARTMENT.Entity;
			}
			set
			{
				TBL_DEPARTMENT previousValue = this._TBL_DEPARTMENT.Entity;
				if (((previousValue != value) 
							|| (this._TBL_DEPARTMENT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_DEPARTMENT.Entity = null;
						previousValue.TBL_EMPLOYEEs.Remove(this);
					}
					this._TBL_DEPARTMENT.Entity = value;
					if ((value != null))
					{
						value.TBL_EMPLOYEEs.Add(this);
						this._fk_dep = value.ID;
					}
					else
					{
						this._fk_dep = default(Nullable<int>);
					}
					this.SendPropertyChanged("TBL_DEPARTMENT");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_COURSE_TRAININGs(TBL_COURSE_TRAINING entity)
		{
			this.SendPropertyChanging();
			entity.TBL_EMPLOYEE = this;
		}
		
		private void detach_TBL_COURSE_TRAININGs(TBL_COURSE_TRAINING entity)
		{
			this.SendPropertyChanging();
			entity.TBL_EMPLOYEE = null;
		}
		
		private void attach_TBL_PARTICIPANT_LISTs(TBL_PARTICIPANT_LIST entity)
		{
			this.SendPropertyChanging();
			entity.TBL_EMPLOYEE = this;
		}
		
		private void detach_TBL_PARTICIPANT_LISTs(TBL_PARTICIPANT_LIST entity)
		{
			this.SendPropertyChanging();
			entity.TBL_EMPLOYEE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_PARTICIPANT_LIST")]
	public partial class TBL_PARTICIPANT_LIST : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _fk_training;
		
		private int _fk_emp;
		
		private int _status;
		
		private System.DateTime _date;
		
		private EntityRef<TBL_COURSE_TRAINING> _TBL_COURSE_TRAINING;
		
		private EntityRef<TBL_EMPLOYEE> _TBL_EMPLOYEE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void Onfk_trainingChanging(int value);
    partial void Onfk_trainingChanged();
    partial void Onfk_empChanging(int value);
    partial void Onfk_empChanged();
    partial void OnstatusChanging(int value);
    partial void OnstatusChanged();
    partial void OndateChanging(System.DateTime value);
    partial void OndateChanged();
    #endregion
		
		public TBL_PARTICIPANT_LIST()
		{
			this._TBL_COURSE_TRAINING = default(EntityRef<TBL_COURSE_TRAINING>);
			this._TBL_EMPLOYEE = default(EntityRef<TBL_EMPLOYEE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_training", DbType="Int NOT NULL")]
		public int fk_training
		{
			get
			{
				return this._fk_training;
			}
			set
			{
				if ((this._fk_training != value))
				{
					if (this._TBL_COURSE_TRAINING.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_trainingChanging(value);
					this.SendPropertyChanging();
					this._fk_training = value;
					this.SendPropertyChanged("fk_training");
					this.Onfk_trainingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_emp", DbType="Int NOT NULL")]
		public int fk_emp
		{
			get
			{
				return this._fk_emp;
			}
			set
			{
				if ((this._fk_emp != value))
				{
					if (this._TBL_EMPLOYEE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_empChanging(value);
					this.SendPropertyChanging();
					this._fk_emp = value;
					this.SendPropertyChanged("fk_emp");
					this.Onfk_empChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int NOT NULL")]
		public int status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="Date NOT NULL")]
		public System.DateTime date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_COURSE_TRAINING_TBL_PARTICIPANT_LIST", Storage="_TBL_COURSE_TRAINING", ThisKey="fk_training", OtherKey="ID", IsForeignKey=true)]
		public TBL_COURSE_TRAINING TBL_COURSE_TRAINING
		{
			get
			{
				return this._TBL_COURSE_TRAINING.Entity;
			}
			set
			{
				TBL_COURSE_TRAINING previousValue = this._TBL_COURSE_TRAINING.Entity;
				if (((previousValue != value) 
							|| (this._TBL_COURSE_TRAINING.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_COURSE_TRAINING.Entity = null;
						previousValue.TBL_PARTICIPANT_LISTs.Remove(this);
					}
					this._TBL_COURSE_TRAINING.Entity = value;
					if ((value != null))
					{
						value.TBL_PARTICIPANT_LISTs.Add(this);
						this._fk_training = value.ID;
					}
					else
					{
						this._fk_training = default(int);
					}
					this.SendPropertyChanged("TBL_COURSE_TRAINING");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_EMPLOYEE_TBL_PARTICIPANT_LIST", Storage="_TBL_EMPLOYEE", ThisKey="fk_emp", OtherKey="ID", IsForeignKey=true)]
		public TBL_EMPLOYEE TBL_EMPLOYEE
		{
			get
			{
				return this._TBL_EMPLOYEE.Entity;
			}
			set
			{
				TBL_EMPLOYEE previousValue = this._TBL_EMPLOYEE.Entity;
				if (((previousValue != value) 
							|| (this._TBL_EMPLOYEE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_EMPLOYEE.Entity = null;
						previousValue.TBL_PARTICIPANT_LISTs.Remove(this);
					}
					this._TBL_EMPLOYEE.Entity = value;
					if ((value != null))
					{
						value.TBL_PARTICIPANT_LISTs.Add(this);
						this._fk_emp = value.ID;
					}
					else
					{
						this._fk_emp = default(int);
					}
					this.SendPropertyChanged("TBL_EMPLOYEE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_ROOM")]
	public partial class TBL_ROOM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _name;
		
		private string _desc;
		
		private string _equip;
		
		private System.Nullable<int> _maxpeople;
		
		private string _place;
		
		private EntitySet<TBL_COURSE_TRAINING> _TBL_COURSE_TRAININGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OndescChanging(string value);
    partial void OndescChanged();
    partial void OnequipChanging(string value);
    partial void OnequipChanged();
    partial void OnmaxpeopleChanging(System.Nullable<int> value);
    partial void OnmaxpeopleChanged();
    partial void OnplaceChanging(string value);
    partial void OnplaceChanged();
    #endregion
		
		public TBL_ROOM()
		{
			this._TBL_COURSE_TRAININGs = new EntitySet<TBL_COURSE_TRAINING>(new Action<TBL_COURSE_TRAINING>(this.attach_TBL_COURSE_TRAININGs), new Action<TBL_COURSE_TRAINING>(this.detach_TBL_COURSE_TRAININGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(255)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[desc]", Storage="_desc", DbType="VarChar(255)")]
		public string desc
		{
			get
			{
				return this._desc;
			}
			set
			{
				if ((this._desc != value))
				{
					this.OndescChanging(value);
					this.SendPropertyChanging();
					this._desc = value;
					this.SendPropertyChanged("desc");
					this.OndescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_equip", DbType="VarChar(255)")]
		public string equip
		{
			get
			{
				return this._equip;
			}
			set
			{
				if ((this._equip != value))
				{
					this.OnequipChanging(value);
					this.SendPropertyChanging();
					this._equip = value;
					this.SendPropertyChanged("equip");
					this.OnequipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxpeople", DbType="Int")]
		public System.Nullable<int> maxpeople
		{
			get
			{
				return this._maxpeople;
			}
			set
			{
				if ((this._maxpeople != value))
				{
					this.OnmaxpeopleChanging(value);
					this.SendPropertyChanging();
					this._maxpeople = value;
					this.SendPropertyChanged("maxpeople");
					this.OnmaxpeopleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_place", DbType="VarChar(255)")]
		public string place
		{
			get
			{
				return this._place;
			}
			set
			{
				if ((this._place != value))
				{
					this.OnplaceChanging(value);
					this.SendPropertyChanging();
					this._place = value;
					this.SendPropertyChanged("place");
					this.OnplaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_ROOM_TBL_COURSE_TRAINING", Storage="_TBL_COURSE_TRAININGs", ThisKey="ID", OtherKey="fk_room")]
		public EntitySet<TBL_COURSE_TRAINING> TBL_COURSE_TRAININGs
		{
			get
			{
				return this._TBL_COURSE_TRAININGs;
			}
			set
			{
				this._TBL_COURSE_TRAININGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_COURSE_TRAININGs(TBL_COURSE_TRAINING entity)
		{
			this.SendPropertyChanging();
			entity.TBL_ROOM = this;
		}
		
		private void detach_TBL_COURSE_TRAININGs(TBL_COURSE_TRAINING entity)
		{
			this.SendPropertyChanging();
			entity.TBL_ROOM = null;
		}
	}
}
#pragma warning restore 1591
